# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: docker:latest

services:
  - docker:dind

variables:
  REGISTRY: "docker.io"
  REGISTRY_USER: "robpco"
  RELEASE_TAG: "latest"
  REGISTRY_IMAGE: "${REGISTRY}/${REGISTRY_USER}/${CI_PROJECT_NAME}:${RELEASE_TAG}"

before_script:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASSWORD"
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

build:
  stage: build
  script:
    - docker pull "${CI_REGISTRY_IMAGE}:latest" || true
    - docker build --cache-from "${CI_REGISTRY_IMAGE}:latest" --tag "${CI_REGISTRY_IMAGE}:${CI_BUILD_REF}" --tag "$REGISTRY_IMAGE" .
    - docker tag "${CI_REGISTRY_IMAGE}:${CI_BUILD_REF}" "${CI_REGISTRY_IMAGE}:latest"
    - docker push "${CI_REGISTRY_IMAGE}:latest"
    - docker push "$REGISTRY_IMAGE"
  only:
    - master
