# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: docker:latest

services:
  - docker:dind

variables:
  REGISTRY: "docker.io"
  REGISTRY_USER: "robpco"
  RELEASE_IMAGE: "awscli"
  RELEASE_TAG: "latest"
  REGISTRY_IMAGE: "${REGISTRY}/${REGISTRY_USER}/${RELEASE_IMAGE}"

before_script:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASSWORD"

build:
  stage: build
  script:
    - docker build --tag "${REGISTRY_IMAGE}:latest" .
    - docker push "${REGISTRY_IMAGE}:latest"
  only:
    - master
